/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelideal.Vistas;

import hotelideal.Conexion;
import hotelideal.Habitacion;
import hotelideal.HabitacionData;
import java.util.ArrayList;
import hotelideal.ModelaTabla;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nancy
 */
public class ListadoHabitaciones extends javax.swing.JInternalFrame {
private DefaultTableModel modelo;
    private ArrayList<Habitacion> listaHabitaciones;
    private HabitacionData habitacionData;
    private Conexion conexion;
    public static String tipo;
    /**
     * Creates new form ListadoHabitaciones
     */
    public ListadoHabitaciones() {
    try {
        initComponents();
        
        conexion=new Conexion("jdbc:mysql://localhost/hotelideal1","root","");
        habitacionData=new HabitacionData(conexion);
        modelo=new DefaultTableModel();
        
        
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(ListadoHabitaciones.class.getName()).log(Level.SEVERE, null, ex);
    }
            cabezeraTabla();
        borrarFilasTabla();
        cargaDatos();
    }
    
    public void cabezeraTabla(){
        ArrayList<Object> columnas=new ArrayList<>();
        columnas.add("Numero");
        columnas.add("Estado");
        columnas.add("Piso");
        columnas.add("Tipo Habitacion");
        columnas.add("Codigo");
        columnas.add("Tipo Cama");
        columnas.add("Nro de Camas");
        columnas.add("Nro de Personas");
        columnas.add("Precio por Noche");
        
        for (Object it:columnas){
            modelo.addColumn(it);
        }
        tablaHabitaciones.setModel(modelo);
        ModelaTabla tbl=new ModelaTabla();
        tbl.modela(tablaHabitaciones);
    }
    
    //******Metodo que borra las filas de la tabla******
    public void borrarFilasTabla(){
        int a =modelo.getRowCount()-1;
        for(int i=a;i>=0;i--){
            modelo.removeRow(i);
        }
    }

    //********Metodo que carga los datos en la tabla********
    public void cargaDatos(){
        listaHabitaciones=(ArrayList)habitacionData.obtenerHabitaciones();
        borrarFilasTabla();
        for (Habitacion r:listaHabitaciones){
            String estado;
            if(r.isEstado()){estado="Libre";}else{estado="Ocupada";}
            modelo.addRow(new Object[]{r.getNumHabitacion(),estado,r.getPiso()
            ,r.getId_tipodehabitacion().getTipo(),r.getId_tipodehabitacion().getCodigo(),
            r.getId_tipodehabitacion().getTipodecama(),r.getId_tipodehabitacion().getCantcamas(),
            r.getId_tipodehabitacion().getCantmaxpersonas(),r.getId_tipodehabitacion().getPrecioxnoche()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaHabitaciones = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setText("LISTADO DE HABITACIONES");

        tablaHabitaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaHabitaciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaHabitaciones;
    // End of variables declaration//GEN-END:variables
}
