/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelideal.Vistas;

import hotelideal.Conexion;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author nancy
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    
     
    public Menu() {
        
        
        initComponents();
        
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jmenuInformeXHuesp = new javax.swing.JMenuBar();
        jmenuHuesp = new javax.swing.JMenu();
        jmenuRegistrarHuesp = new javax.swing.JMenuItem();
        jmenuInforXHuesp = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmenuTipoDeHab = new javax.swing.JMenuItem();
        jmenuGestionHab = new javax.swing.JMenuItem();
        jmenuListadpDeHab = new javax.swing.JMenuItem();
        jmenuGestionarReserva = new javax.swing.JMenu();
        jmenuCrearReserva = new javax.swing.JMenuItem();
        jmenuGestReser = new javax.swing.JMenuItem();
        jmenuArchivo = new javax.swing.JMenu();
        jmenuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelideal/Imagenes/2.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");

        escritorio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jmenuHuesp.setText("HUESPED");

        jmenuRegistrarHuesp.setText("Registrar Huesped");
        jmenuRegistrarHuesp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuRegistrarHuespActionPerformed(evt);
            }
        });
        jmenuHuesp.add(jmenuRegistrarHuesp);

        jmenuInforXHuesp.setText("Informe por Huesped");
        jmenuInforXHuesp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuInforXHuespActionPerformed(evt);
            }
        });
        jmenuHuesp.add(jmenuInforXHuesp);

        jmenuInformeXHuesp.add(jmenuHuesp);

        jMenu2.setText("HABITACIONES");

        jmenuTipoDeHab.setText("Tipo de Habitaciones");
        jmenuTipoDeHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuTipoDeHabActionPerformed(evt);
            }
        });
        jMenu2.add(jmenuTipoDeHab);

        jmenuGestionHab.setText("Gestion de Habitaciones ");
        jmenuGestionHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuGestionHabActionPerformed(evt);
            }
        });
        jMenu2.add(jmenuGestionHab);

        jmenuListadpDeHab.setText("Listado de Habitaciones ");
        jmenuListadpDeHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuListadpDeHabActionPerformed(evt);
            }
        });
        jMenu2.add(jmenuListadpDeHab);

        jmenuInformeXHuesp.add(jMenu2);

        jmenuGestionarReserva.setText("RESERVA");

        jmenuCrearReserva.setText("Crear Reserva");
        jmenuCrearReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuCrearReservaActionPerformed(evt);
            }
        });
        jmenuGestionarReserva.add(jmenuCrearReserva);

        jmenuGestReser.setText("Gestionar Reserva");
        jmenuGestReser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuGestReserActionPerformed(evt);
            }
        });
        jmenuGestionarReserva.add(jmenuGestReser);

        jmenuInformeXHuesp.add(jmenuGestionarReserva);

        jmenuArchivo.setText("ARCHIVO");
        jmenuArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuArchivoActionPerformed(evt);
            }
        });

        jmenuSalir.setText("Salir");
        jmenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuSalirActionPerformed(evt);
            }
        });
        jmenuArchivo.add(jmenuSalir);

        jmenuInformeXHuesp.add(jmenuArchivo);

        setJMenuBar(jmenuInformeXHuesp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmenuRegistrarHuespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuRegistrarHuespActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        RegistrarHuesped rv= new RegistrarHuesped();
        rv.setVisible(true);
        escritorio.add(rv);
        escritorio.moveToFront(rv);
    }//GEN-LAST:event_jmenuRegistrarHuespActionPerformed

    private void jmenuInforXHuespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuInforXHuespActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        InformePorHuesped iph= new InformePorHuesped();
        iph.setVisible(true);
        escritorio.add(iph);
        escritorio.moveToFront(iph);
    }//GEN-LAST:event_jmenuInforXHuespActionPerformed

    private void jmenuTipoDeHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuTipoDeHabActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        VistaTipoDeHabitacion tdh= new VistaTipoDeHabitacion();
        tdh.setVisible(true);
        escritorio.add(tdh);
        escritorio.moveToFront(tdh);
    }//GEN-LAST:event_jmenuTipoDeHabActionPerformed

    private void jmenuGestionHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuGestionHabActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        GestionDeHabitaciones gdh= new GestionDeHabitaciones();
        gdh.setVisible(true);
        escritorio.add(gdh);
        escritorio.moveToFront(gdh);
    }//GEN-LAST:event_jmenuGestionHabActionPerformed

    private void jmenuListadpDeHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuListadpDeHabActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        ListadoHabitaciones lh= new ListadoHabitaciones();
        lh.setVisible(true);
        escritorio.add(lh);
        escritorio.moveToFront(lh);
    }//GEN-LAST:event_jmenuListadpDeHabActionPerformed

    private void jmenuCrearReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuCrearReservaActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        CrearReserva cr= new CrearReserva();
        cr.setVisible(true);
        escritorio.add(cr);
        escritorio.moveToFront(cr);
    }//GEN-LAST:event_jmenuCrearReservaActionPerformed

    private void jmenuGestReserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuGestReserActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        GestionDeReservas gr= new GestionDeReservas();
        gr.setVisible(true);
        escritorio.add(gr);
        escritorio.moveToFront(gr);
    }//GEN-LAST:event_jmenuGestReserActionPerformed
 
    
    
    private void jmenuArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuArchivoActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jmenuArchivoActionPerformed

    private void jmenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuSalirActionPerformed
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_jmenuSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jmenuArchivo;
    private javax.swing.JMenuItem jmenuCrearReserva;
    private javax.swing.JMenuItem jmenuGestReser;
    private javax.swing.JMenuItem jmenuGestionHab;
    private javax.swing.JMenu jmenuGestionarReserva;
    private javax.swing.JMenu jmenuHuesp;
    private javax.swing.JMenuItem jmenuInforXHuesp;
    private javax.swing.JMenuBar jmenuInformeXHuesp;
    private javax.swing.JMenuItem jmenuListadpDeHab;
    private javax.swing.JMenuItem jmenuRegistrarHuesp;
    private javax.swing.JMenuItem jmenuSalir;
    private javax.swing.JMenuItem jmenuTipoDeHab;
    // End of variables declaration//GEN-END:variables
}
