/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelideal.Vistas;

import hotelideal.Conexion;
import hotelideal.ModelaTabla;
import hotelideal.TipoDeHabitacionData;
import hotelideal.TipoDeHabitacion;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nancy
 */
public class VistaTipoDeHabitacion extends javax.swing.JInternalFrame {

    private int id_tipodehabitacion;
    private int codigo;
    private String tipo;
    private Double precioxnoche;
    private int cantmaxpersonas;
    private int cantcamas;
    private String tipodecama;
    private TipoDeHabitacionData tipoDeHabitacionData;
    private Conexion conexion;
    ArrayList<TipoDeHabitacion> listaTipoDeHabitaciones;
    DefaultTableModel modelo;
    /**
     * Creates new form TipoDeHabitacion
     */
    public VistaTipoDeHabitacion() {
        try {
            initComponents();
            conexion = new Conexion("jdbc:mysql://localhost/hotelideal", "root", "");
            tipoDeHabitacionData = new TipoDeHabitacionData(conexion);
            modelo=new DefaultTableModel();
            cabezeraTabla();
            cargarDatos();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VistaTipoDeHabitacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
     public void cabezeraTabla(){
        ArrayList<Object> columnas=new ArrayList<>();
        
        columnas.add("Id");
        columnas.add("Codigo");
        columnas.add("Tipo Habitacion");
        columnas.add("Nro de Personas"); 
        columnas.add("Nro de Camas");
        columnas.add("Tipo Cama");
        columnas.add("Precio por Noche");
        
        for (Object it:columnas){
            modelo.addColumn(it);
        }
        tblTiposHabitaciones.setModel(modelo);
        ModelaTabla mt=new ModelaTabla();
        mt.modelaHabitacion(tblTiposHabitaciones);
    }
        
        //******Metodo que borra las filas de la tabla******
        public void borrarFilasTabla(){
            int a =modelo.getRowCount()-1;
            for(int i=a;i>=0;i--){
                modelo.removeRow(i);
            }
        }

        //********Metodo que carga los datos en la tabla********
        public void cargarDatos(){
            listaTipoDeHabitaciones=(ArrayList)tipoDeHabitacionData.obtenerTipoDeHabitaciones();

            borrarFilasTabla();
            for (TipoDeHabitacion m:listaTipoDeHabitaciones){
              modelo.addRow(new Object[]{m.getId_tipodehabitacion(),m.getCodigo(),m.getTipo(),m.getCantmaxpersonas(),m.getCantcamas(),m.getTipodecama(),m.getPrecioxnoche()});
            }
            
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtCodigo = new javax.swing.JTextField();
        jtCantCamas = new javax.swing.JTextField();
        jtCantPersonas = new javax.swing.JTextField();
        jtPrecioXNoche = new javax.swing.JTextField();
        cbTipoDeHab = new javax.swing.JComboBox<>();
        cbTipoCama = new javax.swing.JComboBox<>();
        jbGuardarTH = new javax.swing.JButton();
        jbBuscarTH = new javax.swing.JButton();
        jbActualizarPrecio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTiposHabitaciones = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setText("REGISTRO DEL TIPO DE HABITACION");

        jLabel2.setText("Codigo");

        jLabel3.setText("Tipo");

        jLabel4.setText("Tipo de Cama");

        jLabel5.setText("Cantidad de Camas");

        jLabel6.setText("Cantidad Personas (Max)");

        jLabel7.setText("Precio por Noche ");

        jtCantCamas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCantCamasActionPerformed(evt);
            }
        });

        cbTipoDeHab.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estándar simple", "Doble", "Triple", "Suite Lujo" }));

        cbTipoCama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Simples", "Queen", "King Size" }));

        jbGuardarTH.setText("Guardar");
        jbGuardarTH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarTHActionPerformed(evt);
            }
        });

        jbBuscarTH.setText("Buscar");
        jbBuscarTH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarTHActionPerformed(evt);
            }
        });

        jbActualizarPrecio.setText("Actualizar Precio");
        jbActualizarPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarPrecioActionPerformed(evt);
            }
        });

        tblTiposHabitaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTiposHabitaciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jbGuardarTH)
                        .addGap(122, 122, 122)
                        .addComponent(jbBuscarTH)
                        .addGap(113, 113, 113)
                        .addComponent(jbActualizarPrecio))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel2)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbTipoCama, 0, 156, Short.MAX_VALUE)
                                    .addComponent(cbTipoDeHab, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtCodigo))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(jLabel6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(jLabel5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(jLabel7)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtPrecioXNoche, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtCantCamas, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtCantPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCantCamas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jtCantPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTipoDeHab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbTipoCama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jtPrecioXNoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbGuardarTH)
                    .addComponent(jbBuscarTH)
                    .addComponent(jbActualizarPrecio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtCantCamasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCantCamasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCantCamasActionPerformed

    private void jbGuardarTHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarTHActionPerformed
        // TODO add your handling code here:
        
        codigo = Integer.parseInt(jtCodigo.getText());
        tipo = (String) cbTipoDeHab.getSelectedItem();       
        cantmaxpersonas= Integer.parseInt(jtCantPersonas.getText());
        cantcamas = Integer.parseInt(jtCantCamas.getText());
        tipodecama = (String) cbTipoCama.getSelectedItem();
         precioxnoche = Double.parseDouble(jtPrecioXNoche.getText());
         
        TipoDeHabitacion tdh = new TipoDeHabitacion(codigo, tipo, cantmaxpersonas, cantcamas, tipodecama,precioxnoche);
        tipoDeHabitacionData.guardarTipoDeHabitacion(tdh);
        JOptionPane.showMessageDialog(null, " El tipo de habitación fue registrado satisfactoriamente ");

        // En blanco los campos de texto y actualiza tabla
         jtCodigo.setText("");
        jtPrecioXNoche.setText("");
        jtCantCamas.setText("");
        jtCantPersonas.setText("");
        borrarFilasTabla();
        cargarDatos();
        
    }//GEN-LAST:event_jbGuardarTHActionPerformed

    private void jbBuscarTHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarTHActionPerformed
        // TODO add your handling code here:
        
         String codigo = JOptionPane.showInputDialog("Ingrese Codigo de Habitacion");
        if(codigo!=null){
            int cod=Integer.parseInt(codigo);
            TipoDeHabitacion tipoDeHabitacion = tipoDeHabitacionData.buscarTipoDeHabitacionXCodigo(cod);
           jtCodigo.setText(tipoDeHabitacion.getCodigo()+"");
            jtPrecioXNoche.setText(tipoDeHabitacion.getPrecioxnoche()+"");
             jtCantCamas.setText(tipoDeHabitacion.getCantcamas()+"");
            jtCantPersonas.setText(tipoDeHabitacion.getCantmaxpersonas()+"");
            tipo=tipoDeHabitacion.getTipo();
            id_tipodehabitacion=tipoDeHabitacion.getId_tipodehabitacion();
            tipodecama=tipoDeHabitacion.getTipodecama();
            cbTipoCama.setSelectedItem(tipodecama);
            cbTipoDeHab.setSelectedItem(tipo);
        }
        
        
        
    }//GEN-LAST:event_jbBuscarTHActionPerformed

    private void jbActualizarPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarPrecioActionPerformed
        // TODO add your handling code here:
        if (jtCodigo.getText().equals("")|| jtCantCamas.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe Buscar un Tipo de Habitacion primero!!!");
        }else{
            tipo = (String) cbTipoDeHab.getSelectedItem();
            precioxnoche = Double.parseDouble(JOptionPane.showInputDialog("Ingrese nuevo Precio"));
             jtPrecioXNoche.setText(precioxnoche+"");
            cantmaxpersonas = Integer.parseInt(jtCantPersonas.getText());
            cantcamas = Integer.parseInt(jtCantCamas.getText());
            tipodecama = (String) cbTipoCama.getSelectedItem();
            codigo=Integer.parseInt( jtCodigo.getText());
        }        
        if (codigo!=0) {
        // actualiza precio     
           TipoDeHabitacion tdh = new TipoDeHabitacion( codigo, tipo, cantmaxpersonas, cantcamas, tipodecama,precioxnoche);
            tipoDeHabitacionData.actualizarTipoDeHabitacion(tdh);
            JOptionPane.showMessageDialog(null, " Datos Actualizado ");
            

        // En blanco los campos de texto y actualiza tabla
        jtCodigo.setText("");
        jtPrecioXNoche.setText("");
        jtCantCamas.setText("");
        jtCantPersonas.setText("");
        borrarFilasTabla();
        cargarDatos();
        }
    }//GEN-LAST:event_jbActualizarPrecioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbTipoCama;
    private javax.swing.JComboBox<String> cbTipoDeHab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbActualizarPrecio;
    private javax.swing.JButton jbBuscarTH;
    private javax.swing.JButton jbGuardarTH;
    private javax.swing.JTextField jtCantCamas;
    private javax.swing.JTextField jtCantPersonas;
    private javax.swing.JTextField jtCodigo;
    private javax.swing.JTextField jtPrecioXNoche;
    private javax.swing.JTable tblTiposHabitaciones;
    // End of variables declaration//GEN-END:variables
}
